### ISSUE TITLE
Data Export and Import to new phone (when applicable)

### ISSUE THREAD

**Issue by githupper** [Demizo/Daily_You#15]
Hi,

I would like to check if the app is capable of exporting and importing. This is to facilitate when the user changes to a new phone and needs the capability to import so as to continue the diary.

Can I confirm if the app as of right now, is capable of exporting and importing by copying the database and image folders to another phone and retains all data?

Thank you

**Comment by Demizo** [comment]
Yes and no. By default the data is stored in the standard android app data folder. This should be covered by any phone export/import tool. If you choose an custom or external storage location the app can't guarantee it will be included in a phone export, but it likely would be. 

The next version will provide more export and import options which will make moving the data easier in the event you need to manually.

**Comment by githupper** [comment]
Maybe I was mistaken but I think most import and export tools nowadays don't work. 

Tools such as Titanium Backup can do it for some apps last time and that's with root access. Seedvault that is used by GrapheneOS and CalyxOS also have limited success during apps restoration with appdata directory hence I prefer that the app data can be stored out to prevent issues with Storage Scope or any app backup tool and the user is able to backup properly himself/herself.

**Comment by Demizo** [comment]
You are probably right, I have never really used those tools so I can't be sure. Since you can set the database and image folder to external storage you can sync/back it up that way. But to keep things simple the next version is offering export/import options. Exporting/importing logs is already ready to merge in but I should also add exporting/importing images before I release.

**Comment by Demizo** [comment]
@nvllz Wow, this is a major oversight on my part. I will make a new top priority issue to add this. It may be a week or so before I get to it unfortunately. For some reason I was under the impression that in-app photos would show in the gallery from which they could be copied, but that is not the case. I didn't notice this since I have only used an external image folder.

If time is of the essence, and you don't have tons of photos, you could use the share button to send the photos to another app. Once you have the photos saved, importing them is less daunting if you just set the image folder to whatever folder directly contains the images (assuming they haven't been renamed). If you want to import them into the app folder again, that process would be manual as of right now as well.

I apologize of this oversight and will fix it as soon as I get the chance!
