### ISSUE TITLE
No-mood option

### ISSUE THREAD

**Issue by nvllz** [Demizo/Daily_You#18]
Now there is a way to add an entry without selecting an emoji, but this way I can see some ⌧ icon now in the place where the mood emoji is displayed. I would like to not indicate my actual mood for some days, but also not have an indicator for no icon. Also, if you add some advanced filtering to the search bar in the future, I'd like to see it as an additional option (to filter by mood emoji) called "no mood".

**Comment by Demizo** [comment]
To clarify, are you asking for a separate indication icon for, "I didn't choose a mood yet" and "I chose to not set a mood for today"? I will spin the filtering by mood into a separate ticket.

**Comment by Demizo** [comment]
Oh no! The no mood icon is a newer emoji "🫥" maybe your browser will show it? Either way I shouldn't use this emoji for compatibility. A no mood option added to the mood picker will be an easy addition and a nice to have. As for having no icon at all, this is tricky since I want some indication on the calendar that a day has been filled out. I'll have to think over what indication makes sense in that case.

**Comment by Demizo** [comment]
I am adding the ability to set custom icons for everything in the next release, so that could be a potential solution

**Comment by Demizo** [comment]
Yeah a question mark keeps it sensible default. With icon picking, I am not restricting it to emojis so any single character will be fair game. If you end up personally wanting no visible icon you can set it to a space 😉

**Comment by Demizo** [comment]
@nvllz #34 adds support for filtering the gallery by mood as requested!
