### ISSUE TITLE
Screen transition bugs

### ISSUE THREAD

**Issue by nvllz** [Demizo/Daily_You#25]
When switching to another screen (Menu > Calendar > Gallery), there is a small blue square in the center of the screen for about ~50 ms.
Additionally, there is a ~50ms rendering delay on the calendar screen, where before the mood icons appear, there are "+" icons in their place. Delayed loading of mood icons causes a little flicker in the animation, and it looks a little bad.

**Comment by Demizo** [comment]
HaHaHa, that little blue square is the start of the loading indicator animation, but that can be removed since the load times aren't really long enough to warrant it. 

As for the mood icons, this is a bit tricky since I am not caching them. I will experiment with it, maybe I can show no icon at all until the mood is known, but there will likely always be a slight delay before the correct icon is displayed.
