### ISSUE TITLE
Sharing Sheet doesnt contain mood

### ISSUE THREAD

**Issue by blaugrau3001** [Demizo/Daily_You#74]
Just a question, in the changelog stands that in the sharing sheet is also the mood but can you say me how, I can't find it when sharing it over Signal.
Otherwise very good implementation as well as this update from 1.7.1 to 1.8

**Comment by Demizo** [comment]
@blaugrau3001 Right now that is because the mood and date are in the "Subject" field which Signal does not respect. A possible approach is to simply add it to the top of the entry text so signal includes it. The downside is that other apps (email, messengers, etc) can take advantage of the subject field. Oh well, I use signal too so this is worth fixing :)
