### ISSUE TITLE
[Bug] Image sync not working

### ISSUE THREAD

**Issue by Rafee-M** [Demizo/Daily_You#80]
After the recent update when trying import images the images, it's has been stuck on this screen.

I have ~10 logs with 10 images.

![Screenshot_2024-01-31-03-20-22-87_b45423ddaf859bff833e028ee8759a0f_1](https://github.com/Demizo/Daily_You/assets/69535896/242a13e4-11f0-4c36-84bc-e4515c3ffdda)

**Comment by Rafee-M** [comment]
Changing the Daily You image folder to the exported folder worked very quickly. 

The previous Daily You version could request all file access, could it be related to that?

**Comment by MrCamel999** [comment]
I would like to report that I am suffering from the exact same issue updating from 1.8.0 to 2.0.1 and trying to restore images.

**Comment by Demizo** [comment]
@MrCamel999 For the sake of reproduction what steps did you take? Did you get stuck importing images or after setting an external folder? If import, had you already set your image and/or log folder when this occured?

**Comment by MrCamel999** [comment]
I got stuck importing images, the screenshot in the original comment for this issue is exactly what I saw. I had not set an image or log folder yet. I did resolve the issue by setting the image folder to the folder where the images were, but that's obviously not ideal. I think it's also important to say that I couldn't select a folder when trying to import, I had to select all 160 images separately (it wasn't too bad to do that, just held on one of them and dragged down the whole folder length). I tried again with only 1 image in case multiple being selected was the issue, but got the same result (note that I reset app data before trying this to make sure I didn't do anything before to break it with only 1 image).

**Comment by Demizo** [comment]
@MrCamel999 Thank you, I'll see if I can recreate it! As for the image import, it is multi-file select rather than folder. If folder select is desirable I may add the option to do either. In the meantime you should be able to hit "select all" once inside the image folder depending on your file explorer. Might save your fingers 👍
