### ISSUE TITLE
Notifications Not Working

### ISSUE THREAD

**Issue by MrCamel999** [Demizo/Daily_You#90]
I'm not sure if this is something I did wrong or an actual bug but I tried my best to make sure it wasn't something on my end. I simply don't get notifications from the app. I have the settings set as such (I changed the time a few times after changing settings to wait for the next minute to see if what I did actually changed anything, don't worry too much about the specific time). The main screen does not have the slash over the notification icon, so that's not the issue. I made sure the app has permission to send notifications, and made sure the battery settings were unrestricted, and I still don't get notifications. Not sure what's up.

![Screenshot_20240206-214620.png](https://github.com/Demizo/Daily_You/assets/44412967/cf3a519e-58cc-4be4-bfcc-65f96fa3bd50)

**Comment by Demizo** [comment]
You know what, now that I think about it, I'm not sure if I have been getting them either. There was probably a regression. I'll look into it!

**Comment by jacksongoode** [comment]
Noticed this too! I need to be reminded! :)

**Comment by blaugrau3001** [comment]
I have the same issue. A thing to add to the app to maybe prevent this type of issue. I'm not very deep in the programming of android apps, but as I understand the app needs the permission alarms and reminders to work with this time based event. Maybe you could add a toast or something that says that you also need to enable this otherwise the feature won't work.
But I have this permission granted and it doesn't work
